# Generated by Django 5.1.3 on 2024-11-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('expected_return_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actual_return', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MATURED', 'Matured'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20)),
                ('documents', models.FileField(blank=True, null=True, upload_to='investment_documents/')),
            ],
        ),
    ]
