# Generated by Django 5.1.3 on 2024-11-14 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_total_savings_member_total_debt_and_more'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='amount_requested',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='amount_approved',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='disbursement_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='total_payable',
        ),
        migrations.RemoveField(
            model_name='loantype',
            name='maximum_amount',
        ),
        migrations.RemoveField(
            model_name='loantype',
            name='maximum_term',
        ),
        migrations.RemoveField(
            model_name='loantype',
            name='minimum_amount',
        ),
        migrations.RemoveField(
            model_name='loantype',
            name='processing_fee',
        ),
        migrations.RemoveField(
            model_name='loantype',
            name='requirements',
        ),
        migrations.AddField(
            model_name='loantype',
            name='category',
            field=models.CharField(choices=[('MEMBER', 'Member Loan'), ('NON_MEMBER', 'Non-Member Loan')], default='MEMBER', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_loans', to='accounts.member'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DEFAULTED', 'Defaulted')], default='PENDING', max_length=20),
        ),
    ]
